### PR TITLE
Reimplement WriteInt using Utf8Formatter to save a string allocation

### PR DESCRIPTION
**Pull request by agehrke**
Uses Utf8Formatter to write int. Adds a test.

### CODE REVIEW

**Comment by agehrke** [comment]
I see I need to clear up some white space and re-add inline attribute.

**Comment by AndyPook** [comment]
nice, I'll will pull this later.

Q what do you think of WriteNumeric in https://github.com/davidfowl/BedrockFramework/blob/d9632c9c66ecfd8a3e6e712a00390a6fd3b1acf9/src/Bedrock.Framework.Experimental/Infrastructure/BufferExtensions.cs ?

**Comment by agehrke** [comment]
Yes, I saw that as well. As we discussed in one of the issues we should probably consider using that BufferWriter from Bedrock. Though the implementation in Bedrock seems somewhat similar to implementation of Utf8Formatter: https://source.dot.net/#System.Private.CoreLib/Utf8Formatter.Integer.Signed.cs,9223c3521ab20ff8

**Comment by AndyPook** [comment]
I do have some WIP that just adds things as extension methods (similar to `WriteNumeric`) . But... `WriteJson` is "tricky" because there's no access to the kinds of things that the json writer needs (which is part of the point of BW, to hide some of the mechanics required to track cursors and "allocate" spans).
But, the other way is to write the json to some other place (ArrayPooledWriter or similar) then copy to the output. The Kafka writer needs a lot of this due to needing to write lengths _before_ the payload.
or just Commit the writer and go direct to the `output` arg of the MessageWriter (but that doesn't feel nice either).

I was really hoping for something that did not require this and just write direct to the "output".

Thoughts?

**Comment by AndyPook** [comment]
decided to stop prevaricating and just get on with it 😄 
removed NatsWriter, converted to BW extensions. Maybe change WriteInt to use WriteNumeric, later

**Pull request merged**
