### PR TITLE
Add tests for WriteJson and writing of ConnectOperation

### PR DESCRIPTION
**Pull request by agehrke**
Adds four tests. Only one of them passes. Will look into getting them to pass as discussed in #1

### CODE REVIEW

**Comment by AndyPook** [comment]
thank you so much for doing this.

I rebased onto the new "master". Only "WriteJson_followed_by_other_writes_must_serialize_object_as_utf8_json_into_buffer" now fails.
I think you've got the `sut.Write(...` line 56 "wrong". For example asci 65 is 'A' not '1' 🤔

**Comment by AndyPook** [comment]
I've also fixed my tests that were failing <oops>
If you rebase on "master" then only the above test fails

**Comment by AndyPook** [comment]
just merged #1 
there's a conflict in NatsWriterTests, should be easy enough to merge/fix

**Comment by agehrke** [comment]
Rebased and fixed one test

**Pull request merged**
